### ISSUE TITLE
Israel needs 12 years contributin

### ISSUE THREAD

**Issue by Br3nda** [ServiceInnovationLab/Piccolo#139]
People who have worked for 0 years are shoing as eligible. This is either a bug in the openfisca rules, or the years they worked aren't being sent to openfisca

**Comment by dlouise64** [comment]
@Br3nda can confirm this is a bug in israel openfisca

**Comment by dlouise64** [comment]
fixed in #139

**Comment by Br3nda** [comment]
Re-opening this - as it's still happening

![image](https://user-images.githubusercontent.com/12266/48097199-06a47d00-e27e-11e8-8ac3-bd80e1ff3333.png)

![image](https://user-images.githubusercontent.com/12266/48097236-26d43c00-e27e-11e8-9d3d-46d6d2f8ee14.png)

**Comment by Br3nda** [comment]
Picolo is sending the correct request to Open Fisca Israel, and Israel replies with `eligible_for_pension: false`. Picolo then incorrectly say you're eligible even though Open Fisca said you were not.
